# Generated by Django 5.0.3 on 2024-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='car_tilte',
            new_name='car_title',
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
