# Generated by Django 5.0.3 on 2024-03-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_car_tilte_contact_car_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cart_id',
            new_name='car_id',
        ),
    ]
